### ISSUE TITLE
drag + drop

### ISSUE THREAD

**Issue by goatandsheep** [goatandsheep/beatcaps-react#42]
* drag-and-drop page for resizable rectangles
* [example](http://jsfiddle.net/Cpvxf/128/)
* [example 2](https://konvajs.org/docs/drag_and_drop/Drag_and_Drop.html)

- [ ] obtain x,y coordinates of top-left of rectangle
- [ ] set height + width
- [ ] also can be set in text boxes rather than drag & drop
- [ ] multiple boxes
- [ ] max 5 rectangles
- [ ] various video resolutions (720p, 1080p, 4K)

![image](https://user-images.githubusercontent.com/5570628/100928209-ec1c4c80-34b3-11eb-9217-3e9e671c6a11.png)

**Comment by goatandsheep** [comment]
I'm thinking we may even separate this from the platform and move it to here https://github.com/goatandsheep/pip-position-demo but not sure yet

**Comment by jiwansidhu** [comment]
yeah makes sense as it is separate module from this repo. Anyway we are not sure yet if we proceed further for this module or will go for lightstream app.

**Comment by goatandsheep** [comment]
@lindajzhao thank you for helping!

I think let's do 3 screen sizes:

* 720p: 1280 x 720
* 1080p: 1920 x 1080
* 4K: 3840 x 2160
